### ISSUE TITLE
Compatibility issue with requirements_3.8

### ISSUE THREAD

**Issue by rbonicel** [BBillot/SynthSeg#52] opened 2023-03-09 15:19 UTC
Hi,

I tried to install the requirements for python3.8 [https://github.com/BBillot/SynthSeg/blob/master/requirements_python3.8.txt] using poetry. I added all packages to the required version, but when I try to install the poetry env, I get the following incompatibility error : 

>   SolverProblemError
> Because opencv-python (4.6.0.66) depends on numpy (>=1.21.2)
>   and database-handling depends on numpy (1.18.5), opencv-python is forbidden.
> So, because database-handling depends on opencv-python (4.6.0.66), version solving failed.

It seems to be an incompatibility between two listed packages in the requirements, between opencv-python==4.6.0.66 and numpy==1.18.5. Should I update numpy to the first version compatible with opencv-python ?

Thanks for your help
Robin

**Comment by BBillot** [comment] 2023-03-16 22:46
Hi,
I noticed this error too, and I have been working to fix it. This is now done and you can have a look at requirements_python3.8.txt for an updated list of dependencies. 
You will notice that it has way fewer dependencies than before, since I've been doing a bit of cleaning in the ext/ folder.
Finally, I've added minimal conda/pip commands in the README to install the correct libraries to make SynthSeg work.
Let me know how it goes.
best
benjamin

**Comment by BBillot** [comment] 2023-03-16 22:50
This issue is not entirely a duplicate of #49, but they're kind of related (issue with python 3.8), so I just thought of mentioning it here :)

**Closed** 2023-03-17 14:22 UTC
