### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by rullator** [BBillot/SynthSeg#92] opened 2024-08-30 09:10 UTC
Hi,

I currently try to install SynthSeg with Python3.8 dependencies.
I followed the README.md but while calling `python ./scripts/commands/SynthSeg_predict.py` I run into the following error:
```shell
(synthseg_38) username@ubuntu-2204:~/Sources/SynthSeg-master$ python ./scripts/commands/SynthSeg_predict.py
/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "./scripts/commands/SynthSeg_predict.py", line 30, in <module>
    from SynthSeg.predict_synthseg import predict
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/SynthSeg-2.0-py3.8.egg/SynthSeg/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/SynthSeg-2.0-py3.8.egg/SynthSeg/brain_generator.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/SynthSeg-2.0-py3.8.egg/SynthSeg/model_inputs.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/SynthSeg-2.0-py3.8.egg/ext/lab2im/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/SynthSeg-2.0-py3.8.egg/ext/lab2im/edit_tensors.py", line 28, in <module>
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.framework import dtypes
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/home/username/anaconda3/envs/synthseg_38/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
``` 

My conda list looks like this:
```shell
(synthseg_38) username@ubuntu-2204:~/Sources/SynthSeg-master$ conda list
# packages in environment at /home/username/anaconda3/envs/synthseg_38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    anaconda
_openmp_mutex             5.1                       1_gnu    anaconda
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.9.5            py38h5eee18b_0    anaconda
aiosignal                 1.2.0              pyhd3eb1b0_0    anaconda
astor                     0.8.1            py38h06a4308_0    anaconda
astunparse                1.6.3                      py_0    anaconda
async-timeout             4.0.3            py38h06a4308_0    anaconda
attrs                     23.1.0           py38h06a4308_0    anaconda
blas                      1.0                         mkl    anaconda
blinker                   1.6.2            py38h06a4308_0    anaconda
brotli                    1.0.9                h5eee18b_8    anaconda
brotli-bin                1.0.9                h5eee18b_8    anaconda
brotli-python             1.0.9            py38h6a678d5_8    anaconda
bzip2                     1.0.8                h5eee18b_6    anaconda
c-ares                    1.19.1               h5eee18b_0    anaconda
ca-certificates           2024.7.2             h06a4308_0    anaconda
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.16.0           py38h5eee18b_1    anaconda
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.7            py38h06a4308_0    anaconda
contourpy                 1.0.7                    pypi_0    pypi
cryptography              43.0.0           py38hdda0065_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
cupti                     10.1.168                      0    anaconda
cycler                    0.11.0             pyhd3eb1b0_0    anaconda
cyrus-sasl                2.1.28               h52b45da_1    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
expat                     2.6.2                h6a678d5_0    anaconda
fontconfig                2.14.1               h55d465d_3    anaconda
fonttools                 4.39.2                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    anaconda
frozenlist                1.4.0            py38h5eee18b_0    anaconda
gast                      0.3.3                      py_0    anaconda
glib                      2.78.4               h6a678d5_0    anaconda
glib-tools                2.78.4               h6a678d5_0    anaconda
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0              pyhd3eb1b0_0    anaconda
grpcio                    1.51.3                   pypi_0    pypi
gst-plugins-base          1.14.1               h6a678d5_1    anaconda
gstreamer                 1.14.1               h5eee18b_1    anaconda
h5py                      2.10.0           py38hd6299e0_1    anaconda
hdf5                      1.10.6               h3ffc7dd_1    anaconda
icu                       73.1                 h6a678d5_0    anaconda
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib_resources       6.4.0            py38h06a4308_0    anaconda
intel-openmp              2023.1.0         hdb19cb5_46306    anaconda
jpeg                      9e                   h5eee18b_3    anaconda
keras                     2.3.1                         0    anaconda
keras-applications        1.0.8                      py_1    anaconda
keras-base                2.3.1                    py38_0    anaconda
keras-preprocessing       1.1.2              pyhd3eb1b0_0    anaconda
kiwisolver                1.4.4            py38h6a678d5_0    anaconda
krb5                      1.20.1               h143b758_1    anaconda
lcms2                     2.12                 h3be6417_0    anaconda
ld_impl_linux-64          2.38                 h1181459_1    anaconda
lerc                      3.0                  h295c915_0    anaconda
libabseil                 20240116.2      cxx17_h6a678d5_0    anaconda
libbrotlicommon           1.0.9                h5eee18b_8    anaconda
libbrotlidec              1.0.9                h5eee18b_8    anaconda
libbrotlienc              1.0.9                h5eee18b_8    anaconda
libclang                  14.0.6          default_hc6dbbc7_1    anaconda
libclang13                14.0.6          default_he11475f_1    anaconda
libcups                   2.4.2                h2d74bed_1    anaconda
libdeflate                1.17                 h5eee18b_1    anaconda
libedit                   3.1.20230828         h5eee18b_0    anaconda
libffi                    3.4.4                h6a678d5_1    anaconda
libgcc-ng                 11.2.0               h1234567_1    anaconda
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libglib                   2.78.4               hdc74915_0    anaconda
libgomp                   11.2.0               h1234567_1    anaconda
libgrpc                   1.62.2               h2d74bed_0    anaconda
libiconv                  1.16                 h5eee18b_3    anaconda
libllvm14                 14.0.6               hdb19cb5_3    anaconda
libpng                    1.6.39               h5eee18b_0    anaconda
libpq                     12.17                hdbd6064_0    anaconda
libprotobuf               4.25.3               he621ea3_0    anaconda
libstdcxx-ng              11.2.0               h1234567_1    anaconda
libtiff                   4.5.1                h6a678d5_0    anaconda
libuuid                   1.41.5               h5eee18b_0    anaconda
libwebp-base              1.3.2                h5eee18b_0    anaconda
libxcb                    1.15                 h7f8727e_0    anaconda
libxkbcommon              1.0.1                h097e994_2    anaconda
libxml2                   2.13.1               hfdd30dd_2    anaconda
lz4-c                     1.9.4                h6a678d5_1    anaconda
markdown                  3.4.1            py38h06a4308_0    anaconda
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-base           3.7.2            py38h1128e8f_0    anaconda
mkl                       2023.1.0         h213fc3f_46344    anaconda
mkl-service               2.4.0            py38h5eee18b_1    anaconda
mkl_fft                   1.3.8            py38h5eee18b_0    anaconda
mkl_random                1.2.4            py38hdb19cb5_0    anaconda
multidict                 6.0.4            py38h5eee18b_0    anaconda
mysql                     5.7.24               h721c034_2    anaconda
ncurses                   6.4                  h6a678d5_0    anaconda
nibabel                   5.0.1                    pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
numpy-base                1.24.3           py38h060ed82_1    anaconda
oauthlib                  3.2.2            py38h06a4308_0    anaconda
openjpeg                  2.5.2                he7f1fd0_0    anaconda
openssl                   3.0.14               h5eee18b_0    anaconda
opt_einsum                3.3.0              pyhd3eb1b0_1    anaconda
packaging                 23.0                     pypi_0    pypi
pcre2                     10.42                hebb0a14_1    anaconda
pillow                    9.4.0                    pypi_0    pypi
pip                       24.2             py38h06a4308_0    anaconda
platformdirs              3.10.0           py38h06a4308_0    anaconda
ply                       3.11                     py38_0    anaconda
pooch                     1.7.0            py38h06a4308_0    anaconda
protobuf                  3.20.3                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0    anaconda
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pyjwt                     2.8.0            py38h06a4308_0    anaconda
pyopenssl                 24.2.1           py38h06a4308_0    anaconda
pyparsing                 3.0.9            py38h06a4308_0    anaconda
pyqt                      5.15.10          py38h6a678d5_0    anaconda
pyqt5-sip                 12.13.0          py38h5eee18b_0    anaconda
pysocks                   1.7.1            py38h06a4308_0    anaconda
python                    3.8.19               h955ad1f_0    anaconda
python-dateutil           2.8.2                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
qt-main                   5.15.2              h53bd1ea_10    anaconda
re2                       2022.04.01           h295c915_0    anaconda
readline                  8.2                  h5eee18b_0    anaconda
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                72.1.0           py38h06a4308_0    anaconda
sip                       6.7.12           py38h6a678d5_0    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
sqlite                    3.45.3               h5eee18b_0    anaconda
tbb                       2021.8.0             hdb19cb5_0    anaconda
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-data-server   0.7.0            py38h52d8a92_1    anaconda
tensorboard-plugin-wit    1.8.1            py38h06a4308_0    anaconda
tensorflow                2.2.0           gpu_py38hb782248_0    anaconda
tensorflow-base           2.2.0           gpu_py38h83e3d50_0    anaconda
tensorflow-estimator      2.2.0                    pypi_0    pypi
tensorflow-gpu            2.2.0                    pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0    anaconda
tomli                     2.0.1            py38h06a4308_0    anaconda
tornado                   6.4.1            py38h5eee18b_0    anaconda
unicodedata2              15.1.0           py38h5eee18b_0    anaconda
urllib3                   1.26.15                  pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0    anaconda
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
yarl                      1.9.3            py38h5eee18b_0    anaconda
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    anaconda
zstd                      1.5.5                hc292b87_2    anaconda
``` 

Can anybody help?

**Comment by joseabernal** [comment] 2024-09-05 14:17
I am having exactly the same problem. It looks like the tensorflow-gpu version is part of the problem. I set the tensorflow-gpu version to 2.1.0 and removed the TensorBoard callback in "training.py" and was able to run "3-training.py".

**Comment by neuronflow** [comment] 2024-09-23 13:41
seems related to https://github.com/BBillot/SynthSeg/issues/93#issuecomment-2368206469

**Comment by BBillot** [comment] 2024-09-23 18:57
exactly, this issue is a duplicate of #93 
Closing this down for now ;)

**Closed as completed by BBillot** 2024-09-23 18:57 UTC

**Comment by rullator** [comment] 2024-09-30 08:27
Thanks for addressing the issue!
Is it fixed in the latest release?
